### ISSUE TITLE
General: gcloud crashes when run within virtualenv even if CLOUDSDK_PYTHON is set correctly

### ISSUE THREAD

**Issue by benkuhn** [GoogleCloudPlatform/google-cloud-python#5173]
This started happening immediately after upgrading to 196.0.0 and kept happening when I reinstalled:

```
 ~ % gcloud version
Google Cloud SDK 196.0.0
bq 2.0.31
core 2018.03.30
gsutil 4.30
 ~ % mkvirtualenv gcloudfail
Using base prefix '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/ben/.virtualenvs/gcloudfail/bin/python3.6
Also creating executable in /Users/ben/.virtualenvs/gcloudfail/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/ben/.virtualenvs/gcloudfail/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/ben/.virtualenvs/gcloudfail/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/ben/.virtualenvs/gcloudfail/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/ben/.virtualenvs/gcloudfail/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/ben/.virtualenvs/gcloudfail/bin/get_env_details
(gcloudfail)  ~ % declare -p CLOUDSDK_PYTHON
export CLOUDSDK_PYTHON=/usr/local/bin/python2.7
(gcloudfail)  ~ % $CLOUDSDK_PYTHON --version
Python 2.7.13
(gcloudfail)  ~ % gcloud version         
ERROR: gcloud failed to load: cannot import name json_format
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.calliope import base
    from googlecloudsdk.calliope import display
    from googlecloudsdk.calliope import display_taps
    from googlecloudsdk.core.resource import resource_printer_base
    from googlecloudsdk.core.resource import resource_projector
    from google.protobuf import json_format as protobuf_encoding

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 executable:
    /usr/local/opt/python/bin/python2.7

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/
(gcloudfail)  ~ 1 % /usr/local/opt/python/bin/python2.7 --version
Python 2.7.13
(gcloudfail)  ~ % /usr/local/bin/python2.7 -S /Users/ben/bin/google-cloud-sdk/lib/gcloud.py version 
Google Cloud SDK 196.0.0
bq 2.0.31
core 2018.03.30
gsutil 4.30
(gcloudfail)  ~ %
```

I'm running macOS High Sierra 10.13.3. Using zsh in case that matters. `pip show google-cloud` does not show any output although `gcloud version` works fine outside of a virtualenv or with `-S` passed.

**Comment by tseaver** [comment]
@benkuhn I'm sorry you are having trouble with the `gcloud` CLI.  Unfortunately, the `google-cloud-*` packages are libraries for Python application development, and are entirely separate from the `gcloud` command-line package and the SDK.  Please report issues with the CLI/SDK to [its tracker](https://issuetracker.google.com/issues/new?component=187143&template=800102).

**Comment by benkuhn** [comment]
Oh rats! Sorry for the noise, not sure how I ended up in the wrong place.
