### ISSUE TITLE
Pubsub: 'thread_name_prefix' error

### ISSUE THREAD

**Issue by kerighan** [GoogleCloudPlatform/google-cloud-python#6008]
Hi !

I have installed and upgraded google cloud (Im' working on Python 2.7), but whenever I try to create a SubscriberClient object, I get the following error : TypeError: __init__() got an unexpected keyword argument 'thread_name_prefix'

This happens on my machine but also on Google Compute engines. This error comes from the fact that the concurrent.futures.ThreadPoolExecutor class does not have a "thread_name_prefix" argument.

Do you have a solution for my error ? Can you reproduce it ? Thank you very much for your help !

**Comment by tseaver** [comment]
Can you please provide the complete traceback?  Also, the output from `pip freeze`?

**Comment by tseaver** [comment]
The [release notes for google-cloud-pubsub 0.29.3](https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/pubsub-0.29.3) note (in the "Dependencies" section):

> Upgrading google-api-core dependency to latest revision (0.1.2) since we rely on the latest version of the concurrent.futures backport to provide the thread_name_prefix argument for thread pool executor (#4521, #4559).

Please try in a fresh virtual environment, or else upgrade the dependencies in your current environment.
