### PR TITLE
Updating datastore HTTP wrapper.

### LINKED ISSUE #4387: Datastore: unexpected keyword arg in DS client
Commit 9246de7a7138fabb3f25dceb50715de445684323 introduced following bug:
```
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/datastore/client.py", line 321, in get
    eventual=eventual)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/datastore/client.py", line 376, in get_multi
    transaction_id=transaction and transaction.id,
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/datastore/client.py", line 138, in _extended_lookup
    keys=key_pbs,
TypeError: lookup() got an unexpected keyword argument 'project_id'
```

Patch
```diff
From 7470329ecf13d9f85bfe8af71ee533856ff9ec4c Mon Sep 17 00:00:00 2001
From: mathewcohle <mathewcohle@gmail.com>
Date: Mon, 13 Nov 2017 11:41:01 +0100
Subject: [PATCH] Fix wrong keyword argument name introduced in #4348

---
 datastore/google/cloud/datastore/client.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/datastore/google/cloud/datastore/client.py b/datastore/google/cloud/datastore/client.py
index a3d1f9d43..c42c75e32 100644
--- a/datastore/google/cloud/datastore/client.py
+++ b/datastore/google/cloud/datastore/client.py
@@ -133,7 +133,7 @@ def _extended_lookup(datastore_api, project, key_pbs,
     while loop_num < _MAX_LOOPS:  # loop against possible deferred.
         loop_num += 1
         lookup_response = datastore_api.lookup(
-            project_id=project,
+            project=project,
             read_options=read_options,
             keys=key_pbs,
         )
-- 
2.15.0
```

Info (datastore installed from current master via `pip install git+https://github.com/GoogleCloudPlatform/google-cloud-python.git#subdirectory=datastore`)
```
$ pip freeze | grep google

gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
google-api-core==0.1.1
google-api-python-client==1.6.4
google-auth==1.2.0
google-cloud==0.30.1.dev1
google-cloud-bigquery==0.28.0
google-cloud-bigtable==0.28.1
google-cloud-core==0.28.0
google-cloud-datastore==1.4.1.dev1
google-cloud-dns==0.28.0
google-cloud-error-reporting==0.28.0
google-cloud-firestore==0.28.0
google-cloud-language==1.0.0
google-cloud-logging==1.4.0
google-cloud-monitoring==0.28.0
google-cloud-pubsub==0.29.0
google-cloud-resource-manager==0.28.0
google-cloud-runtimeconfig==0.28.0
google-cloud-spanner==0.29.0
google-cloud-speech==0.30.0
google-cloud-storage==1.6.0
google-cloud-trace==0.16.0
google-cloud-translate==1.3.0
google-cloud-videointelligence==0.28.0
google-cloud-vision==0.28.0
google-gax==0.12.5
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
grpc-google-iam-v1==0.11.4
grpc-google-logging-v2==0.8.1
grpc-google-pubsub-v1==0.8.1
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
```

### PR DESCRIPTION
**Pull request by dhermes**
- Making the method arguments (both in position and name) match the arguments for `google.cloud.datastore_v1.gapic.datastore_client.DatastoreClient`
- Passing positional as positional and keyword as keyword when using the low-level API client in `Client.get()` (was previously using all keyword arguments to `.lookup()`, which caused this issue)
- Updating mock call assertions to match the change in calling behavior.

Fixes #4387.

### CODE REVIEW

**Comment by dhermes** [comment]
When I checked the `datastore_client.DatastoreClient` interface, this also revealed

- Our low-level HTTP client doesn't have `retry=` or `timeout=` keywords (@jonparrott any good ideas here?)
- Our low-level HTTP client doesn't support the `reserve_ids` method

**Comment by dhermes** [comment]
@tseaver I think it's "good form" to do. With the addition of keyword-only arguments in Python 3, I'm not so sure that's a common attitude. From my perspective, using positional as positional and keyword as keyword actually indicates that the knows that.

Also, this isn't the first time we've been bitten by the auto-generated interface changing, which is why I advocate for "strict" adherence the offered interface.

PS What's B&D?

**Comment by tseaver** [comment]
@dhermes note that I approved the PR:  I'm just "arguing with the ref."

> Also, this isn't the first time we've been bitten by the auto-generated interface changing, which is why I advocate for "strict" adherence the offered interface.

They are equally capable of breaking this usage (changing order of "positional" arguments, for instance, which would be covered by using *only* keyword args when calling them).

B&D -> "bondage-and-discipline".
