### ISSUE TITLE
AttributeError: 'Iterator' object has no attribute 'item_to_value' in datastore/query.py page_iterator.Page

### ISSUE THREAD

**Issue by wsh** [GoogleCloudPlatform/google-cloud-python#5169]
_From @bialoglowy on March 24, 2018 9:52_

I'm getting the following AttributeError error in datastore/query.py:

```
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/env/lib/python3.6/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/home/vmagent/app/sec_api/rest/resources/project.py", line 1281, in on_get
    raise ex
  File "/home/vmagent/app/sec_api/rest/resources/project.py", line 1243, in on_get
    _results = self.resource.stats()
  File "/home/vmagent/app/sec_api/resources/project.py", line 98, in wrapper
    return f(*args, **kwds)
  File "/home/vmagent/app/sec_api/resources/project.py", line 816, in stats
    _all = self.storage.all(keys_only=False)
  File "/home/vmagent/app/sec_api/storage.py", line 1207, in all
    keys_only=keys_only)
  File "/home/vmagent/app/sec_api/storage.py", line 125, in wrapper
    raise _ex
  File "/home/vmagent/app/sec_api/storage.py", line 108, in wrapper
    return f(*args, **kwds)
  File "/home/vmagent/app/sec_api/storage.py", line 1232, in _get_all
    for entity in query_iter:
  File "/env/lib/python3.6/site-packages/google/api_core/page_iterator.py", line 186, in _items_iter
    for page in self._page_iter(increment=False):
  File "/env/lib/python3.6/site-packages/google/api_core/page_iterator.py", line 217, in _page_iter
    page = self._next_page()
  File "/env/lib/python3.6/site-packages/google/cloud/datastore/query.py", line 518, in _next_page
    return page_iterator.Page(self, entity_pbs, self.item_to_value)
AttributeError: 'Iterator' object has no attribute 'item_to_value'
```

It happens in the following code:
```
    def all(self, exclude_deleted=True):
        _query = self.client.query(kind=self.kind)
        _all = []
        query_iter = _query.fetch()
        for entity in query_iter:
            _all.append(entity)
```

Application is deployed on Google App Engine with the following requirements.txt:

```
google-gax==0.16.0
google-cloud==0.32.0
google-cloud-core==0.28.1
google-cloud-datastore==1.6.0
google-cloud-pubsub==0.33.0
google-cloud-storage==1.8.0

```

_Copied from original issue: GoogleCloudPlatform/google-cloud-datastore#200_

**Comment by wsh** [comment]
_From @daniiln on March 30, 2018 18:35_

experiencing the same issus after updated to the latest datastore library
```
from google.cloud import datastore
kind = 'blah'
datastore_client = datastore.Client()
query = datastore_client.query(kind=kind)
queryset = list(query.fetch())
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniil/enviroments/wh2/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 186, in _items_iter
    for page in self._page_iter(increment=False):
  File "/Users/daniil/enviroments/wh2/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 217, in _page_iter
    page = self._next_page()
  File "/Users/daniil/enviroments/wh2/lib/python2.7/site-packages/google/cloud/datastore/query.py", line 518, in _next_page
    return page_iterator.Page(self, entity_pbs, self.item_to_value)
AttributeError: 'Iterator' object has no attribute 'item_to_value'
```

**Comment by wsh** [comment]
_From @dkavraal on March 31, 2018 19:56_

Dropped to 1.5.0, then it works.
google-cloud-datastore==1.5.0

**Comment by wsh** [comment]
_From @bialoglowy on April 4, 2018 6:53_

Correct, it works on google-cloud-datastore==1.5.0.

**Comment by wsh** [comment]
Hey there! I'm sorry you're experiencing this issue, but the driver you're having issues with is part of [google-cloud-python](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/datastore). The Python driver in this repo (package name `googledatastore`) is totally separate. Please re-file this issue there and the google-cloud-python team will investigate. Sorry for the confusing situation.

**Comment by tseaver** [comment]
The base class (`google.api_core.page_iterator.Iterator`) defines an `item_to_value` attribute explicitly.  What version of `google.api_core` do you have installed?  E.g.:

```bash
$ /path/to/venv/bin/pip show google.api_core
```

**Comment by yiga2** [comment]
`1.1.0`

Datastore 1.6 requirement is `google-api-core[grpc]<2.0.0dev,>=1.0.0`

**Comment by tseaver** [comment]
I cannot reproduce in a fresh virtualenv, using a [script like yours](https://gist.github.com/tseaver/c9d9ff4594cd11a64b31b86b0c75bc51) which pre-populates entities of the given kind before querying:

```bash
$ /opt/Python-3.6.3/bin/python3 -m venv /tmp/gcp-5169
$ /tmp/gcp-5169/bin/pip install --upgrade setuptools pip wheel
Collecting setuptools
...
Successfully installed pip-9.0.3 setuptools-39.0.1 wheel-0.31.0
$ /tmp/gcp-5169/bin/pip install "google-cloud-datastore==1.6.0"
Collecting google-cloud-datastore==1.6.0
  Downloading google_cloud_datastore-1.6.0-py2.py3-none-any.whl (76kB)
    100% |████████████████████████████████| 81kB 333kB/s 
...
Successfully installed cachetools-2.0.1 certifi-2018.1.18 chardet-3.0.4 google-api-core-1.1.0 google-auth-1.4.1 google-cloud-core-0.28.1 google-cloud-datastore-1.6.0 googleapis-common-protos-1.5.3 grpcio-1.10.1 idna-2.6 protobuf-3.5.2.post1 pyasn1-0.4.2 pyasn1-modules-0.2.1 pytz-2018.4 requests-2.18.4 rsa-3.4.2 six-1.11.0 urllib3-1.22
$ /tmp/gcp-5169/bin/pip list | grep google
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
google-api-core (1.1.0)
google-auth (1.4.1)
google-cloud-core (0.28.1)
google-cloud-datastore (1.6.0)
googleapis-common-protos (1.5.3)
$ /tmp/gcp-5169/bin/python /tmp/gcp-5169/repro_gcp_5169.py 
showme: 1
showme: 2
showme: 3
showme: 4
showme: 5
showme: 6
showme: 7
showme: 8
showme: 9
showme: 10
```

**Comment by yiga2** [comment]
Weird - with the above code and mine (airflow), I don't have an error anymore. 

I am not the OP, @bialoglowy is. @dkavraal and @daniiln reported the issue too so I let them chime in - if they are monitor this.

**Comment by tseaver** [comment]
@wsh, @bialoglowy I cannot reproduce the error with the following:

```bash
$ /opt/Python-3.6.3/bin/python3 -m venv /tmp/gcp-5169
$ cd /tmp/gcp-5169/
$ bin/pip install --upgrade setuptools wheel pip
...
Successfully installed pip-10.0.1 setuptools-39.2.0 wheel-0.31.1
$ bin/pip install google-cloud-datastore
...
Successfully installed cachetools-2.1.0 certifi-2018.4.16 chardet-3.0.4 google-api-core-1.2.0 google-auth-1.4.2 google-cloud-core-0.28.1 google-cloud-datastore-1.6.0 googleapis-common-protos-1.5.3 grpcio-1.12.0 idna-2.6 protobuf-3.5.2.post1 pyasn1-0.4.3 pyasn1-modules-0.2.1 pytz-2018.4 requests-2.18.4 rsa-3.4.2 six-1.11.0 urllib3-1.22
$ bin/pip freeze | grep google
google-api-core==1.2.0
google-auth==1.4.2
google-cloud-core==0.28.1
google-cloud-datastore==1.6.0
googleapis-common-protos==1.5.3
$ wget https://gist.github.com/tseaver/c9d9ff4594cd11a64b31b86b0c75bc51/raw/84b148d5a2217fe6f39d05882721d05ed6996659/repro_gcp_5169.py
...
2018-05-31 16:04:56 (29.8 MB/s) - ‘repro_gcp_5169.py’ saved [384/384]
$ export GOOGLE_APPLICATION_CREDENTIALS=....
$ bin/python repro_gcp_5169.py 
showme: 1
showme: 2
showme: 3
showme: 4
showme: 5
showme: 6
showme: 7
showme: 8
showme: 9
showme: 10
```

Please reopen if you can figure out how to reproduce the error you are seeing.

**Comment by eneumann** [comment]
@tseaver 

I am running into this error after upgrading to py3. I've tried the current stable versions of datastore, cloud-storage, and bigquery. After reading this, I've gone back to older version and still have the same error.

Last attempt reqs:
google-api-core==1.1.0
google-api-python-client==1.5.3
google-apitools==0.5.4
google-auth==1.6.3
google-cloud==0.34.0
google-cloud-bigquery==0.30.0
google-cloud-core==0.28.1
google-cloud-datastore==1.6.0
google-cloud-storage==1.8.0
google-resumable-media==0.3.2
googleapis-common-protos==1.6.0
grpcio==1.22.0

Traceback (most recent call last):
  File "/home/manzama/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/manzama/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/manzama/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/manzama/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/manzama/manzama/website/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/manzama/manzama/apps/content/management/commands/refresh_local.py", line 46, in handle
    for doc in Document.q_all():
  File "/home/manzama/manzama/apps/documents/base.py", line 438, in q_all
    itr = query.fetch(limit, *args, **kwargs)
  File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/google/cloud/datastore/query.py", line 382, in fetch
    eventual=eventual)
  File "/home/manzama/manzama/apps/documents/query.py", line 38, in __init__
    super(PagedIterator, self).__init__(*args, **kwargs)
  File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/google/cloud/datastore/query.py", line 423, in __init__
    page_token=start_cursor, max_results=limit)
TypeError: __init__() got an unexpected keyword argument 'item_to_value'

**Comment by tseaver** [comment]
@eneumann You need to upgrade at least `googe-api-core`.  I would actually suggest creating a fresh virtualenv, and installing exactly what you need there *without* version pins, e.g., via `pip install google-cloud-datastore google-cloud-storage google-cloud-bigquery`.

**Comment by eneumann** [comment]
Thanks @tseaver, I installed to a clean virtualenv without pins which resulted in the following versions:
google-api-core==1.13.0
google-api-python-client==1.7.9
google-apitools==0.5.30
google-auth==1.6.3
google-auth-httplib2==0.0.3
google-cloud==0.34.0
google-cloud-bigquery==1.17.0
google-cloud-core==1.0.2
google-cloud-datastore==1.8.0
google-cloud-storage==1.16.1
google-resumable-media==0.3.2
googleapis-common-protos==1.6.0
grpcio==1.0.0

Unfortunately I'm still getting the same error -> 
    default: Traceback (most recent call last):
    default:   File "/home/manzama/manzama/website/manage.py", line 11, in <module>
    default:     execute_from_command_line(sys.argv)
    default:   File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    default:     utility.execute()
    default:   File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    default:     self.fetch_command(subcommand).run_from_argv(self.argv)
    default:   File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    default:     self.execute(*args, **cmd_options)
    default:   File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    default:     output = self.handle(*args, **options)
    default:   File "/home/manzama/manzama/apps/content/management/commands/refresh_local.py", line 46, in handle
    default:     for doc in Document.q_all():
    default:   File "/home/manzama/manzama/apps/documents/base.py", line 438, in q_all
    default:     itr = query.fetch(limit, *args, **kwargs)
    default:   File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/google/cloud/datastore/query.py", line 392, in fetch
    default:     eventual=eventual,
    default:   File "/home/manzama/manzama/apps/documents/query.py", line 38, in __init__
    default:     super(PagedIterator, self).__init__(*args, **kwargs)
    default:   File "/home/manzama/.virtualenvs/mzpy3/lib/python3.5/site-packages/google/cloud/datastore/query.py", line 444, in __init__
    default:     max_results=limit,
    default: TypeError: __init__() got an unexpected keyword argument 'item_to_value'

**Comment by tseaver** [comment]
@eneumann I cannot reproduce.  First, setting up the virtual environment

```bash
$ python3.6 -m venv /tmp/gcp/5169 
$ /tmp/gcp/5169/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-19.1.1 setuptools-41.0.1 wheel-0.33.4
$ /tmp/gcp/5169/bin/pip install google-cloud-datastore google-cloud-bigquery google-cloud-storage
,,,
Successfully installed cachetools-3.1.1 certifi-2019.6.16 chardet-3.0.4 google-api-core-1.13.0 google-auth-1.6.3 google-cloud-bigquery-1.17.0 google-cloud-core-1.0.2 google-cloud-datastore-1.8.0 google-cloud-storage-1.16.1 google-resumable-media-0.3.2 googleapis-common-protos-1.6.0 grpcio-1.22.0 idna-2.8 protobuf-3.9.0 pyasn1-0.4.5 pyasn1-modules-0.2.5 pytz-2019.1 requests-2.22.0 rsa-4.0 six-1.12.0 urllib3-1.25.3
$ /tmp/gcp/5169/bin/pip list
Package                  Version  
------------------------ ---------
cachetools               3.1.1    
certifi                  2019.6.16
chardet                  3.0.4    
google-api-core          1.13.0   
google-auth              1.6.3    
google-cloud-bigquery    1.17.0   
google-cloud-core        1.0.2    
google-cloud-datastore   1.8.0    
google-cloud-storage     1.16.1   
google-resumable-media   0.3.2    
googleapis-common-protos 1.6.0    
grpcio                   1.22.0   
idna                     2.8      
pip                      19.1.1   
protobuf                 3.9.0    
pyasn1                   0.4.5    
pyasn1-modules           0.2.5    
pytz                     2019.1   
requests                 2.22.0   
rsa                      4.0      
setuptools               41.0.1   
six                      1.12.0   
urllib3                  1.25.3   
wheel                    0.33.4 
$ /tmp/gcp/5169/bin/python
```

Now, creating and iterating over a Datastore query:

```python
>>> from google.cloud.datastore import Client
>>> client = Client()
>>> query = client.query(kind='MyKind')
>>> list(query.fetch())
[]
```

Is it possible you left the "old" virtual environment activated?

**Comment by eneumann** [comment]
Thanks @tseaver, I'm installing to a vagrant vm after doing a vagrant destroy. Perhaps destroy isn't blowing away all the files that I'd assume it would?

**Comment by eneumann** [comment]
@tseaver we had monkey patched datastore.query.Iterator to an extended iterator of our own which was failing on the inner api-core init super. I was able to fix it by copying the datastore.query Iterator class to our repo and then extending it. Not sure why it couldn't handle from an import? Anyway it's working now and I appreciate your time and sanity checks. Thanks.
