### ISSUE TITLE
Issue with logging and google-auth

### ISSUE THREAD

**Issue by tcroiset** [GoogleCloudPlatform/google-cloud-python#3931]
The following code:
```
import google.cloud.logging
import logging

from google.cloud.logging.handlers import CloudLoggingHandler

client = google.cloud.logging.Client()
handler = CloudLoggingHandler(client)
cloud_logger = logging.getLogger()
cloud_logger.setLevel(logging.INFO)
cloud_logger.addHandler(handler)
cloud_logger.addHandler(logging.StreamHandler())
cloud_logger.info('hello')
```

works fine with google-cloud-logging==1.1.0 but fails with newer versions (1.2.0 or 1.3.0) :
```
Failed to submit 1 logs.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/handlers/transports/background_thread.py", line 99, in _safely_commit_batch
    batch.commit()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/logger.py", line 549, in commit
    client.logging_api.write_entries(entries, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/_http.py", line 163, in write_entries
    self.api_request(method='POST', path='/entries:write', data=data)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 290, in api_request
    headers=headers, target_object=_target_object)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 183, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 212, in _do_request
    url=url, method=method, headers=headers, data=data)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 175, in request
    self.credentials.before_request(
AttributeError: 'AuthorizedSession' object has no attribute 'credentials'

```

**Comment by dhermes** [comment]
Trying to repro right now.

**Comment by dhermes** [comment]
@tcroiset I can't reproduce. Can you step into a debugger and inspect `self` / `pp self.__dict__` at the moment of failure? I usually just run code in IPython and then hop into the stacktrace with the `%debug` magic.

**Comment by tcroiset** [comment]
```
self:

<google.auth.transport.requests.AuthorizedSession object at 0x7fce6777bb90>
```

```
self.__dict__: 

 {
     'cookies': < RequestsCookieJar[] > ,
     'stream': False,
     'hooks': {
         'response': []
     },
     'auth': None,
     'trust_env': True,
     'headers': {
         'Connection': 'keep-alive',
         'Accept-Encoding': 'gzip, deflate',
         'Accept': '*/*',
         'User-Agent': 'python-requests/2.18.4'
     },
     'cert': None,
     'params': {},
     'prefetch': None,
     'verify': True,
     'proxies': {},
     'adapters': OrderedDict([('https://', < requests.adapters.HTTPAdapter object at 0x7fce6777bd50 > ), ('http://', < requests.adapters.HTTPAdapter object at 0x7fce6771a090 > )]),
     'max_redirects': 30
 }
```

**Comment by dhermes** [comment]
@tcroiset Thanks a lot!

@jonparrott Any ideas?

**Comment by jonparrott** [comment]
Can I get the output of `pip freeze` @tcroiset?

**Comment by tcroiset** [comment]
cachetools==2.0.1
certifi==2017.7.27.1
chardet==3.0.4
colorama==0.3.2
dill==0.2.7.1
enum34==1.1.6
future==0.16.0
futures==3.1.1
gapic-google-cloud-logging-v2==0.91.3
google-auth==1.0.2
google-cloud-core==0.27.1
google-cloud-logging==1.3.0
google-gax==0.15.14
googleapis-common-protos==1.5.2
grpcio==1.6.0
html5lib==0.999
httplib2==0.10.3
idna==2.6
mercurial==3.1.2
oauth2client==3.0.0
ply==3.8
proto-google-cloud-logging-v2==0.91.3
protobuf==3.4.0
pyasn1==0.3.4
pyasn1-modules==0.1.4
requests==2.18.4
rsa==3.4.2
six==1.10.0
urllib3==1.22
virtualenv==15.0.3

**Comment by jonparrott** [comment]
Hrm I can't repro either. Can you tell me a bit more info?

* Python version
* OS
* Which type of credentials you're using (`import google.auth; print(google.auth.default())`)

**Comment by tcroiset** [comment]
Here is the dockerfile I use
(It's based on an appengine image because in my full code, it's an appengine app with a worker and a monitor like https://cloud.google.com/python/getting-started/tutorial-app)

```
FROM gcr.io/google_appengine/python

RUN apt-get update && apt-get install -y emacs
ADD requirements.txt /app/
RUN pip install -r requirements.txt

ADD . /app
ADD MyServiceAccount.json /cred/
ENV GOOGLE_APPLICATION_CREDENTIALS "/cred/MyServiceAccount.json"
ENV GOOGLE_CLOUD_DISABLE_GRPC true
CMD python my.py
```

**Comment by tcroiset** [comment]
Hum, I just noticed that it is linked with GOOGLE_CLOUD_DISABLE_GRPC.
If I remove it, the error doesn't occur.

**Comment by jonparrott** [comment]
Ah, it's probably [this line](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/handlers/transports/background_thread.py#L257) which is a relic from when httplib2 was used as it wasn't threadsafe. We can probably just remove that.

@liyanhui1228 Can you take this?

**Comment by liyanhui1228** [comment]
Sure! I can take this. Sorry for the late reply, I'm looking into this right now.
