### PR TITLE
Remove deepcopy of client._http

### LINKED ISSUE #3931: Issue with logging and google-auth
The following code:
```
import google.cloud.logging
import logging

from google.cloud.logging.handlers import CloudLoggingHandler

client = google.cloud.logging.Client()
handler = CloudLoggingHandler(client)
cloud_logger = logging.getLogger()
cloud_logger.setLevel(logging.INFO)
cloud_logger.addHandler(handler)
cloud_logger.addHandler(logging.StreamHandler())
cloud_logger.info('hello')
```

works fine with google-cloud-logging==1.1.0 but fails with newer versions (1.2.0 or 1.3.0) :
```
Failed to submit 1 logs.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/handlers/transports/background_thread.py", line 99, in _safely_commit_batch
    batch.commit()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/logger.py", line 549, in commit
    client.logging_api.write_entries(entries, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/_http.py", line 163, in write_entries
    self.api_request(method='POST', path='/entries:write', data=data)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 290, in api_request
    headers=headers, target_object=_target_object)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 183, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 212, in _do_request
    url=url, method=method, headers=headers, data=data)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 175, in request
    self.credentials.before_request(
AttributeError: 'AuthorizedSession' object has no attribute 'credentials'

```

### PR DESCRIPTION
**Pull request by liyanhui1228**
Fixes #3931.
When GOOGLE_CLOUD_DISABLE_GRPC=true, the logging will have `'AuthorizedSession' object has no attribute 'credentials'` exception.
The line `http = copy.deepcopy(client._http)` is a relic when httplib2 was used. Removing it and directly use the `client` passed in instead of re-initialize with the deepcopied http object solved the problem.

### CODE REVIEW

File: logging/google/cloud/logging/handlers/transports/background_thread.py [hunk 1]
```diff
@@ -254,9 +253,7 @@ class BackgroundThreadTransport(Transport):
 
     def __init__(self, client, name, grace_period=_DEFAULT_GRACE_PERIOD,
                  batch_size=_DEFAULT_MAX_BATCH_SIZE):
-        http = copy.deepcopy(client._http)
-        self.client = client.__class__(
-            client.project, client._credentials, http)
+        self.client = client
```
Comment (dhermes) [inline logging/google/cloud/logging/handlers/transports/background_thread.py]: Is the copy completely un-needed now? Was the lack of thread-safety in `httplib2` the sole reason for copying?

**Comment by lukesneeringer** [comment]
Side note: CODEOWNERS does not seem to work quite right. :-(

**Comment by lukesneeringer** [comment]
On the merits of this actual PR -- this does look sane to me, but hoping @tseaver or @jonparrott will make sure I am not missing something obvious.

File: logging/google/cloud/logging/handlers/transports/background_thread.py (hunk 1 above)
Comment (jonparrott) [reply logging/google/cloud/logging/handlers/transports/background_thread.py]: Yeah that was my wild guess here and it seems it was correct. :)

Comment (liyanhui1228) [reply logging/google/cloud/logging/handlers/transports/background_thread.py]: I didn't have much context about the reason for deepcopying the http object. I have tried reproduce this using `google-cloud-core==0.26.0`(which switched from `httplib2` to `requests` as the HTTP transport) and `google-cloud-logging==1.2.0`(which depends on core 0.26.0), and the same exception occurred. But it would not occur with an earlier version. And removing the deepcopy of http can solve the issue here. Still investigating if there are any other reason for deepcopying and ensure it's safe to remove it. Maybe the original author @waprin can share some idea here?

Comment (jonparrott) [reply logging/google/cloud/logging/handlers/transports/background_thread.py]: We indeed deepcopied this because of thread-safety concerns.

Comment (waprin) [reply logging/google/cloud/logging/handlers/transports/background_thread.py]: what @jonparrott said :)

**Comment by waprin** [comment]
The original deepcopy was a race condition for the async long handler, but it's covered in the system test, being a race condition it didn't always appear but it did frequently enough that if there's any problem with the PR you'd probably know soon. LGTM if jon think it look right.

**Comment by liyanhui1228** [comment]
Thanks @waprin! I have run the system tests for several times locally and it works fine. Though the race condition does not always appear as Bill said. If thread-safety is the only reason for deepcopy, sounds like we can safely remove it. Can we go ahead and merge this?

**Comment by liyanhui1228** [comment]
The system test `test_create_sink_pubsub_topic` failed with error message `from google.cloud.pubsub import client as pubsub_client    ImportError: cannot import name client`, which seems need to be updated to match the recent pubsub changes. Probably fix it in another PR?

**Comment by lukesneeringer** [comment]
@liyanhui1228 Go ahead and fix that here. Happy to merge once tests pass.

**Comment by liyanhui1228** [comment]
Ready for merging, system tests passed locally.

```
tests/system.py::TestLogging::test_create_metric PASSED
tests/system.py::TestLogging::test_create_sink_bigquery_dataset PASSED
tests/system.py::TestLogging::test_create_sink_pubsub_topic PASSED
tests/system.py::TestLogging::test_create_sink_storage_bucket PASSED
tests/system.py::TestLogging::test_list_entry_with_unregistered PASSED
tests/system.py::TestLogging::test_list_metrics PASSED
tests/system.py::TestLogging::test_list_sinks PASSED
tests/system.py::TestLogging::test_log_handler_async _has_entries. Trying again in 1 seconds...
PASSED
tests/system.py::TestLogging::test_log_handler_sync _has_entries. Trying again in 1 seconds...
PASSED
tests/system.py::TestLogging::test_log_root_handler It was the best of times.
_has_entries. Trying again in 1 seconds...
_has_entries. Trying again in 2 seconds...
PASSED
tests/system.py::TestLogging::test_log_struct _has_entries. Trying again in 1 seconds...
PASSED
tests/system.py::TestLogging::test_log_struct_w_metadata _has_entries. Trying again in 1 seconds...
PASSED
tests/system.py::TestLogging::test_log_text _has_entries. Trying again in 1 seconds...
PASSED
tests/system.py::TestLogging::test_log_text_w_metadata _has_entries. Trying again in 1 seconds...
PASSED
tests/system.py::TestLogging::test_log_text_with_resource _has_entries. Trying again in 1 seconds...
PASSED
tests/system.py::TestLogging::test_log_text_with_timestamp _has_entries. Trying again in 1 seconds...
PASSED
tests/system.py::TestLogging::test_reload_metric PASSED
tests/system.py::TestLogging::test_reload_sink PASSED
tests/system.py::TestLogging::test_update_metric PASSED
tests/system.py::TestLogging::test_update_sink PASSED
```
